/**
 * 02_enrich_catalog_steps.js
 * --------------------------
 * Añade pasos (steps) a los 18 platos del catálogo que tienen steps: null
 *   - mediterranean-pack-vol1  (8 platos)
 *   - mexican-pack-vol1        (10 platos)
 *
 * También añade: description, prepTime, cookTime, difficulty, allergens, tags
 * a nivel de plato (campos directamente en el subdocumento dish).
 *
 * Usage:
 *   node 02_enrich_catalog_steps.js          # dry-run
 *   node 02_enrich_catalog_steps.js --apply  # commit
 */

import { MongoClient, ObjectId } from "mongodb";
import { resolveMongoUrl } from "../mongo-url.js";

const APPLY = process.argv.includes("--apply");
const NOW = new Date();

// ─── ENRIQUECIMIENTO POR dishTemplateId ──────────────────────────────────────
// Cada entrada: { description, prepTime, cookTime, difficulty, allergens, tags, steps[] }
const DISH_ENRICHMENT = {

  // ────────────────────────────────────────────────────────────────────────────
  // MEDITERRANEAN PACK
  // ────────────────────────────────────────────────────────────────────────────

  "ensalada-griega-7cfcfa9a": {
    description: "Ensalada vibrante y refrescante con los colores del Mediterráneo: tomate jugoso, pepino crujiente, aceitunas kalamata y un generoso bloque de queso feta que se desmenuza con el tenedor. Un clásico griego que nunca decepciona.",
    prepTime: 15,
    cookTime: 0,
    difficulty: "Fácil",
    allergens: ["lactosa"],
    tags: ["griega", "sin gluten", "vegetariana", "verano", "sin cocción"],
    steps: [
      {
        order: 1,
        title: "Prepara las verduras",
        text: "Corta los tomates en gajos gruesos o medios lunas. Corta el pepino en rodajas de 1 cm con piel o sin piel al gusto. Lamina la cebolla roja en aros muy finos — para suavizar el sabor, sumérge los aros en agua fría 10 min.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [{ name: "Tomate" }, { name: "Pepino" }, { name: "Cebolla roja" }],
      },
      {
        order: 2,
        title: "Monta la ensalada",
        text: "En una fuente amplia, coloca los tomates como base. Distribuye el pepino y los aros de cebolla roja por encima de forma irregular para que cada bocado mezcle sabores.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [{ name: "Tomate" }, { name: "Pepino" }, { name: "Cebolla roja" }],
      },
      {
        order: 3,
        title: "Añade aceitunas y feta",
        text: "Reparte las aceitunas negras kalamata por toda la superficie. Desmenuzha el queso feta en trozos irregulares de 2-3 cm y colócalo encima sin mezclar para conservar su textura.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [{ name: "Aceitunas negras" }, { name: "Queso feta" }],
      },
      {
        order: 4,
        title: "Aliña y sirve",
        text: "Rocía con aceite de oliva virgen extra generosamente, añade orégano seco al gusto y una pizca de sal (cuidado — el feta ya sala bastante). Sirve inmediatamente o refrigera máx. 30 min antes.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [],
      },
    ],
  },

  "hummus-con-pan-de-pita-5a55bdf8": {
    description: "Crema de garbanzos aterciopelada con tahini, limón y ajo que se prepara en el procesador en minutos. Servida con pan de pita caliente para mojar, es un aperitivo irresistible con raíces en Oriente Medio.",
    prepTime: 10,
    cookTime: 5,
    difficulty: "Fácil",
    allergens: ["gluten", "sésamo"],
    tags: ["mediterráneo", "vegetariano", "aperitivo", "sin lactosa", "proteico"],
    steps: [
      {
        order: 1,
        title: "Prepara los garbanzos",
        text: "Escurre y enjuaga los garbanzos cocidos. Guarda 4-5 cucharadas del líquido de la lata (aquafaba) en un vaso — ayudará a conseguir la textura perfecta.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [{ name: "Garbanzos cocidos" }],
      },
      {
        order: 2,
        title: "Tritura el hummus",
        text: "Coloca en el procesador los garbanzos, tahini, zumo del limón, los dientes de ajo pelados y una pizca de sal. Tritura 1 min. Añade el aquafaba reservado cucharada a cucharada hasta conseguir una pasta muy suave. Rectifica de sal y limón.",
        hasTimer: true,
        durationMinutes: 1,
        durationSeconds: null,
        timerLabel: "Triturado",
        ingredientRefs: [{ name: "Garbanzos cocidos" }, { name: "Tahini" }, { name: "Limón" }, { name: "Ajo" }],
      },
      {
        order: 3,
        title: "Presenta el plato",
        text: "Extiende el hummus en un plato hondo formando un remolino con el dorso de la cuchara. Haz un pequeño hueco en el centro y vierte un hilo de aceite de oliva. Espolvorea pimentón y comino al gusto.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [],
      },
      {
        order: 4,
        title: "Calienta el pan de pita",
        text: "Calienta las pitas directamente en el fuego de gas 30 seg por lado, o en tostador/horno a 180°C durante 3-4 min. Deben quedar hinchadas y ligeramente doradas.",
        hasTimer: true,
        durationMinutes: 4,
        durationSeconds: null,
        timerLabel: "Hornear pitas",
        ingredientRefs: [{ name: "Pan de pita" }],
      },
      {
        order: 5,
        title: "Sirve",
        text: "Sirve el hummus junto a las pitas calientes cortadas en triángulos. Acompaña con pepino, aceitunas o pimientos si deseas.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [],
      },
    ],
  },

  "pasta-al-pesto-99a76ae8": {
    description: "Pasta italiana con pesto genovés recién hecho: albahaca fresca, piñones tostados, parmesano y ajo ligados con aceite de oliva virgen extra. Una salsa vibrante que solo necesita la calidad de sus ingredientes.",
    prepTime: 15,
    cookTime: 12,
    difficulty: "Fácil",
    allergens: ["gluten", "lactosa", "frutos secos"],
    tags: ["italiana", "pasta", "vegetariana", "pesto", "rápido"],
    steps: [
      {
        order: 1,
        title: "Cuece la pasta",
        text: "Pon a hervir abundante agua con sal generosa (debe saber casi a mar). Cuece la pasta al dente según el paquete. Antes de escurrir, reserva 1 taza del agua de cocción.",
        hasTimer: true,
        durationMinutes: 10,
        durationSeconds: null,
        timerLabel: "Cocción pasta",
        ingredientRefs: [{ name: "Pasta" }],
      },
      {
        order: 2,
        title: "Tuesta los piñones",
        text: "Calienta una sartén seca a fuego medio. Añade los piñones y remueve constantemente 2-3 min hasta que estén dorados y fragantes. Retira enseguida — se queman rápido.",
        hasTimer: true,
        durationMinutes: 3,
        durationSeconds: null,
        timerLabel: "Tostar piñones",
        ingredientRefs: [{ name: "Piñones" }],
      },
      {
        order: 3,
        title: "Prepara el pesto",
        text: "En el vaso de la batidora o mortero, tritura la albahaca fresca con los piñones tostados, el ajo, el parmesano rallado, sal y el aceite de oliva. Debe quedar una salsa densa. Rectifica de sal.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [{ name: "Albahaca fresca" }, { name: "Piñones" }, { name: "Parmesano rallado" }, { name: "Ajo" }],
      },
      {
        order: 4,
        title: "Mezcla pasta y pesto",
        text: "Escurre la pasta y pásala a la cazuela retirada del fuego. Añade el pesto y 3-4 cdas del agua de cocción reservada. Mezcla con movimientos envolventes — el calor residual integra la salsa sin cocinarla.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [{ name: "Pasta" }],
      },
      {
        order: 5,
        title: "Sirve inmediatamente",
        text: "Reparte en platos hondos calientes. Añade más parmesano rallado y unos piñones por encima. El pesto nunca debe recalentarse — sirve siempre al momento.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [{ name: "Parmesano rallado" }, { name: "Piñones" }],
      },
    ],
  },

  "pollo-al-limon-con-oregano-1f2f15a5": {
    description: "Pollo marinado en limón, ajo y orégano griego que se hornea hasta conseguir una piel crujiente y dorada con una carne jugosa que se desprende del hueso. El aroma que llena la cocina lo dice todo.",
    prepTime: 15,
    cookTime: 45,
    difficulty: "Fácil",
    allergens: [],
    tags: ["griega", "horno", "sin gluten", "sin lactosa", "familiar"],
    steps: [
      {
        order: 1,
        title: "Prepara la marinada",
        text: "Mezcla en un bol el zumo y la ralladura de los 2 limones, el ajo picado fino, el orégano, el aceite de oliva, sal generosa y pimienta negra molida. Bate hasta integrar.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [{ name: "Limón" }, { name: "Ajo" }, { name: "Orégano seco" }, { name: "Aceite de oliva" }],
      },
      {
        order: 2,
        title: "Marina el pollo",
        text: "Seca bien las piezas de pollo con papel de cocina — la piel seca es clave para que cruja. Unta toda la superficie con la marinada. Deja reposar al menos 30 min a temperatura ambiente o 2h en nevera.",
        hasTimer: true,
        durationMinutes: 30,
        durationSeconds: null,
        timerLabel: "Marinado mínimo",
        ingredientRefs: [{ name: "Pollo en piezas" }],
      },
      {
        order: 3,
        title: "Precalienta el horno",
        text: "Precalienta el horno a 200 °C con calor arriba y abajo. Coloca las piezas de pollo en bandeja con la piel hacia arriba, sin amontonar. Vierte la marinada restante por la bandeja.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [],
      },
      {
        order: 4,
        title: "Hornea el pollo",
        text: "Hornea 35-40 min. A mitad de cocción, baña las piezas con los jugos de la bandeja. El pollo está listo cuando la piel esté dorada y crujiente, y la temperatura interior llegue a 75 °C en la parte más gruesa.",
        hasTimer: true,
        durationMinutes: 40,
        durationSeconds: null,
        timerLabel: "Horneado",
        ingredientRefs: [{ name: "Pollo en piezas" }],
      },
      {
        order: 5,
        title: "Reposa y sirve",
        text: "Deja reposar el pollo 5 min fuera del horno para que los jugos se redistribuyan. Sirve con los jugos de la bandeja por encima y rodajas de limón fresco.",
        hasTimer: true,
        durationMinutes: 5,
        durationSeconds: null,
        timerLabel: "Reposo",
        ingredientRefs: [],
      },
    ],
  },

  "shakshuka-2a57eff9": {
    description: "Huevos pochados directamente en una salsa especiada de tomate, pimiento y comino de origen norteafricano. Un plato vibrante que se sirve directamente en la sartén y conquista en el primer bocado.",
    prepTime: 10,
    cookTime: 25,
    difficulty: "Fácil",
    allergens: ["huevo"],
    tags: ["norteafricano", "sin gluten", "sin lactosa", "brunch", "vegetariano"],
    steps: [
      {
        order: 1,
        title: "Sofríe la base",
        text: "Calienta 2 cdas de aceite en sartén grande o cazuela de hierro a fuego medio. Sofríe la cebolla picada 5-6 min hasta que esté translúcida y blanda.",
        hasTimer: true,
        durationMinutes: 6,
        durationSeconds: null,
        timerLabel: "Sofrito cebolla",
        ingredientRefs: [{ name: "Cebolla" }],
      },
      {
        order: 2,
        title: "Añade el pimiento y especias",
        text: "Incorpora el pimiento rojo en dados y cocina 5 min. Añade el comino, pimentón dulce y una pizca de cayena. Remueve 1 min para tostar las especias y liberar sus aromas.",
        hasTimer: true,
        durationMinutes: 6,
        durationSeconds: null,
        timerLabel: "Pimiento + especias",
        ingredientRefs: [{ name: "Pimiento rojo" }, { name: "Comino molido" }],
      },
      {
        order: 3,
        title: "Cuece la salsa de tomate",
        text: "Vierte el tomate triturado, salpimenta y cocina a fuego medio-bajo 10 min removiendo ocasionalmente hasta que la salsa espese y pierda acidez. Rectifica sal.",
        hasTimer: true,
        durationMinutes: 10,
        durationSeconds: null,
        timerLabel: "Reducción salsa",
        ingredientRefs: [{ name: "Tomate triturado" }],
      },
      {
        order: 4,
        title: "Añade los huevos",
        text: "Con una cuchara, crea 4 huecos en la salsa. Casca un huevo en cada hueco con cuidado. Salpimenta solo las yemas.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [{ name: "Huevos" }],
      },
      {
        order: 5,
        title: "Cuece los huevos",
        text: "Tapa la sartén y cocina a fuego bajo 6-8 min según preferencia: 6 min para yema líquida, 8 min para cuajada. Las claras deben estar completamente blancas.",
        hasTimer: true,
        durationMinutes: 7,
        durationSeconds: null,
        timerLabel: "Cocción huevos",
        ingredientRefs: [{ name: "Huevos" }],
      },
      {
        order: 6,
        title: "Sirve en la sartén",
        text: "Lleva la sartén directamente a la mesa. Espolvorea perejil o cilantro picado y un chorro de aceite. Acompaña con pan de pita o pan crujiente para mojar.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [],
      },
    ],
  },

  "risotto-de-seta-c9e81a79": {
    description: "Arroz arbóreo cremoso con setas variadas salteadas, cocinado en caldo cuchara a cuchara hasta conseguir esa textura sedosa que caracteriza al gran risotto italiano. Terminado con parmesano y mantequilla.",
    prepTime: 15,
    cookTime: 30,
    difficulty: "Media",
    allergens: ["lactosa"],
    tags: ["italiana", "sin gluten", "vegetariano", "cremoso", "especial"],
    steps: [
      {
        order: 1,
        title: "Prepara el caldo caliente",
        text: "Calienta el caldo de verduras en un cazo y mantenlo caliente a fuego mínimo durante toda la cocción. El caldo frío corta la cocción del arroz.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [{ name: "Caldo de verduras" }],
      },
      {
        order: 2,
        title: "Saltea las setas",
        text: "En cazuela amplia, derrite 20 g de mantequilla con un chorro de aceite a fuego fuerte. Saltea las setas variadas 5-6 min sin remover demasiado para que se doren bien. Salpimenta. Retira y reserva.",
        hasTimer: true,
        durationMinutes: 6,
        durationSeconds: null,
        timerLabel: "Saltear setas",
        ingredientRefs: [{ name: "Setas variadas" }],
      },
      {
        order: 3,
        title: "Sofríe la cebolla y el arroz",
        text: "En la misma cazuela, reduce el fuego a medio y sofríe la cebolla picada fina en 20 g de mantequilla 5 min. Añade el arroz arbóreo y remueve 2 min hasta que esté nacarado y translúcido en los bordes.",
        hasTimer: true,
        durationMinutes: 7,
        durationSeconds: null,
        timerLabel: "Sofrito + nacarado",
        ingredientRefs: [{ name: "Cebolla" }, { name: "Arroz arbóreo" }],
      },
      {
        order: 4,
        title: "Cocina el risotto",
        text: "Añade un cacillo de caldo caliente al arroz y remueve suavemente. Cuando se absorba casi por completo, añade otro cacillo. Repite el proceso durante 16-18 min removiendo con frecuencia. El risotto debe estar al dente.",
        hasTimer: true,
        durationMinutes: 18,
        durationSeconds: null,
        timerLabel: "Cocción risotto",
        ingredientRefs: [{ name: "Caldo de verduras" }, { name: "Arroz arbóreo" }],
      },
      {
        order: 5,
        title: "Incorpora las setas y el parmesano",
        text: "Añade las setas salteadas reservadas y el parmesano rallado. Remueve. El risotto debe tener consistencia cremosa y fluida (\"all'onda\" — que se mueva como una ola al mover la cazuela).",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [{ name: "Setas variadas" }, { name: "Parmesano rallado" }],
      },
      {
        order: 6,
        title: "Mantecatura y servicio",
        text: "Retira del fuego. Añade 20 g de mantequilla fría en dados y remueve con energía 1 min (mantecatura). Sirve inmediatamente en platos hondos calientes con más parmesano y un hilo de aceite de trufa opcional.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [],
      },
    ],
  },

  "merluza-al-horno-con-tomate-f4562afd": {
    description: "Lomos de merluza jugosos horneados sobre una cama de tomates cherry asados con aceitunas y ajo. Un plato de pescado ligero y aromático que se hace en 25 minutos con ingredientes del Mediterráneo.",
    prepTime: 10,
    cookTime: 22,
    difficulty: "Fácil",
    allergens: ["pescado"],
    tags: ["pescado", "horno", "sin gluten", "sin lactosa", "saludable", "rápido"],
    steps: [
      {
        order: 1,
        title: "Prepara la cama de verduras",
        text: "Precalienta el horno a 200 °C. En bandeja de horno, coloca los tomates cherry cortados por la mitad, el ajo laminado y las aceitunas negras. Rocía con 2 cdas de aceite, sal y pimienta. Hornea solos 10 min.",
        hasTimer: true,
        durationMinutes: 10,
        durationSeconds: null,
        timerLabel: "Precoc. verduras",
        ingredientRefs: [{ name: "Tomates cherry" }, { name: "Ajo" }, { name: "Aceitunas negras" }],
      },
      {
        order: 2,
        title: "Prepara el pescado",
        text: "Seca los lomos de merluza con papel de cocina. Salpimenta generosamente por ambos lados.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [{ name: "Lomos de merluza" }],
      },
      {
        order: 3,
        title: "Hornea la merluza",
        text: "Coloca los lomos de merluza sobre la cama de verduras precocinada. Rocía con el aceite restante. Hornea 12-15 min hasta que la merluza esté opaca y se separe fácilmente con un tenedor. No sobrecocines.",
        hasTimer: true,
        durationMinutes: 13,
        durationSeconds: null,
        timerLabel: "Horneado merluza",
        ingredientRefs: [{ name: "Lomos de merluza" }],
      },
      {
        order: 4,
        title: "Sirve en la bandeja",
        text: "Sirve directamente en la bandeja o traslada a una fuente. Añade perejil fresco picado y un chorro de aceite de oliva virgen extra en crudo. Acompaña con pan crujiente para el jugo.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [],
      },
    ],
  },

  "lentejas-con-verdura-d9511934": {
    description: "Lentejas cocinadas desde cero con zanahoria, apio y cebolla en una salsa de tomate que espesa durante la cocción. Un plato de legumbres sencillo, nutritivo y reconfortante que mejora de un día para otro.",
    prepTime: 15,
    cookTime: 35,
    difficulty: "Fácil",
    allergens: [],
    tags: ["legumbres", "vegetariano", "vegano", "sin gluten", "económico"],
    steps: [
      {
        order: 1,
        title: "Sofríe la base aromática",
        text: "En olla grande, calienta 3 cdas de aceite a fuego medio. Sofríe la cebolla picada 5 min. Añade el ajo, la zanahoria en rodajas y el apio en trozos. Cocina 5 min más removiendo.",
        hasTimer: true,
        durationMinutes: 10,
        durationSeconds: null,
        timerLabel: "Sofrito base",
        ingredientRefs: [{ name: "Cebolla" }, { name: "Zanahoria" }, { name: "Apio" }],
      },
      {
        order: 2,
        title: "Añade las lentejas y el tomate",
        text: "Incorpora las lentejas lavadas, el tomate triturado, laurel, comino, sal y pimienta. Añade agua fría hasta cubrir 3 dedos por encima de todo.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [{ name: "Lentejas" }, { name: "Tomate triturado" }],
      },
      {
        order: 3,
        title: "Cuece las lentejas",
        text: "Lleva a ebullición, reduce el fuego y cuece tapado 25-30 min hasta que las lentejas estén tiernas. Remueve ocasionalmente y añade agua si se quedara seco.",
        hasTimer: true,
        durationMinutes: 28,
        durationSeconds: null,
        timerLabel: "Cocción lentejas",
        ingredientRefs: [{ name: "Lentejas" }],
      },
      {
        order: 4,
        title: "Ajusta y sirve",
        text: "Prueba y rectifica sal. Para dar más cuerpo, retira un cazo de lentejas, tritura y devuelve a la olla. Sirve con un chorro de aceite de oliva virgen extra y comino al gusto.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [],
      },
    ],
  },

  // ────────────────────────────────────────────────────────────────────────────
  // MEXICAN PACK
  // ────────────────────────────────────────────────────────────────────────────

  "tacos-de-pollo-58ee4f49": {
    description: "Tacos callejeros con pollo marinado en especias, tortillas de maíz tostadas al momento, cebolla cruda y cilantro fresco que aportan contraste. El chorro de lima al final lo une todo en un bocado perfecto.",
    prepTime: 20,
    cookTime: 15,
    difficulty: "Fácil",
    allergens: ["gluten"],
    tags: ["mexicano", "taco", "sin lactosa", "familiar", "picante-opcional"],
    steps: [
      {
        order: 1,
        title: "Marina y cocina el pollo",
        text: "Corta el pollo en tiras finas. Sazona con sal, pimienta, comino y pimentón. Calienta sartén con aceite a fuego fuerte y cocina el pollo 6-8 min en tandas sin amontonar — debe dorar, no hervir. Reserva.",
        hasTimer: true,
        durationMinutes: 8,
        durationSeconds: null,
        timerLabel: "Cocción pollo",
        ingredientRefs: [{ name: "Pollo" }],
      },
      {
        order: 2,
        title: "Prepara los toppings",
        text: "Pica la cebolla muy fina en dados pequeños. Pica el cilantro fresco. Corta las limas en gajos. Si tienes jalapeños o salsa picante, prepáralos también.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [{ name: "Cebolla" }, { name: "Cilantro fresco" }, { name: "Lima" }],
      },
      {
        order: 3,
        title: "Calienta las tortillas",
        text: "Calienta las tortillas de maíz directamente sobre el fuego de gas 30 seg por lado, o en sartén seca a fuego fuerte. Deben abombar e inflarse ligeramente — señal de que están frescas.",
        hasTimer: true,
        durationMinutes: 1,
        durationSeconds: null,
        timerLabel: "Calentar tortillas",
        ingredientRefs: [{ name: "Tortillas de maíz" }],
      },
      {
        order: 4,
        title: "Monta los tacos",
        text: "Coloca 2-3 tiras de pollo en el centro de cada tortilla. Añade cebolla picada, cilantro generoso y exprime un gajo de lima por encima.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [{ name: "Pollo" }, { name: "Cebolla" }, { name: "Cilantro fresco" }, { name: "Lima" }],
      },
      {
        order: 5,
        title: "Sirve inmediatamente",
        text: "Sirve los tacos en el momento — la tortilla debe estar caliente. Acompaña con salsa verde, guacamole y jalapeños en escabeche para que cada comensal personalice.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [],
      },
    ],
  },

  "enchiladas-verd-6846b77d": {
    description: "Tortillas de maíz enrolladas con pollo desmenuzado y bañadas en salsa verde de tomatillo, gratinadas en el horno hasta que la salsa burbujea. Terminadas con crema agria y queso fresco para equilibrar el picante.",
    prepTime: 20,
    cookTime: 25,
    difficulty: "Media",
    allergens: ["gluten", "lactosa"],
    tags: ["mexicano", "horno", "sin gluten*", "familiar", "picante"],
    steps: [
      {
        order: 1,
        title: "Precalienta el horno",
        text: "Precalienta el horno a 180 °C. Engrasa ligeramente una fuente de horno rectangular.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [],
      },
      {
        order: 2,
        title: "Prepara el relleno",
        text: "Si el pollo aún no está cocinado, cuécelo o saltéalo con sal, comino y ajo en polvo 10 min. Desmenúzalo con dos tenedores. Mezcla con 2-3 cdas de salsa verde para humedecerlo.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [{ name: "Pollo desmenuzado" }, { name: "Salsa verde" }],
      },
      {
        order: 3,
        title: "Ablanda las tortillas",
        text: "Calienta las tortillas en sartén seca 30 seg por lado para que sean flexibles sin romperse. Trabaja de una en una manteniéndolas calientes.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [{ name: "Tortillas de maíz" }],
      },
      {
        order: 4,
        title: "Rellena y enrolla",
        text: "Coloca 2-3 cdas de pollo desmenuzado en el centro de cada tortilla. Enrolla firmemente y coloca con la unión hacia abajo en la fuente. Repite hasta llenar.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [{ name: "Pollo desmenuzado" }, { name: "Tortillas de maíz" }],
      },
      {
        order: 5,
        title: "Baña y hornea",
        text: "Cubre completamente las enchiladas con la salsa verde restante. Hornea 20 min hasta que burbujee. Los últimos 5 min, espolvorea el queso fresco desmenuzado.",
        hasTimer: true,
        durationMinutes: 20,
        durationSeconds: null,
        timerLabel: "Horneado",
        ingredientRefs: [{ name: "Salsa verde" }, { name: "Queso fresco" }],
      },
      {
        order: 6,
        title: "Finaliza y sirve",
        text: "Saca del horno y añade la crema agria en hilo, cebolla morada picada y cilantro fresco. Sirve inmediatamente con arroz blanco.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [{ name: "Crema agria" }],
      },
    ],
  },

  "guacamole-con-nacho-12843229": {
    description: "Guacamole artesano con aguacate maduro machacado a mano, tomate fresco, cebolla y cilantro. Servido al momento con nachos crujientes para que cada chip recoja toda la cremosidad verde.",
    prepTime: 15,
    cookTime: 0,
    difficulty: "Fácil",
    allergens: [],
    tags: ["mexicano", "vegano", "sin gluten", "sin lactosa", "aperitivo", "sin cocción"],
    steps: [
      {
        order: 1,
        title: "Abre y vacía los aguacates",
        text: "Corta los aguacates por la mitad, retira el hueso (guárdalo) y extrae la pulpa con una cuchara. Comprueba que estén completamente maduros — deben ceder suavemente al presionar.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [{ name: "Aguacate maduro" }],
      },
      {
        order: 2,
        title: "Machaca el aguacate",
        text: "Machaca la pulpa en un bol con tenedor o molcajete. La textura debe ser semi-gruesa: sin trozos grandes pero con algo de cuerpo — nunca un puré liso.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [{ name: "Aguacate maduro" }],
      },
      {
        order: 3,
        title: "Añade los ingredientes frescos",
        text: "Pica el tomate en dados muy pequeños sin semillas. Pica la cebolla finísima. Pica el cilantro fresco. Mezcla todo con el aguacate. Añade zumo de lima, sal y jalapeño picado al gusto.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [{ name: "Tomate" }, { name: "Cebolla" }, { name: "Cilantro" }],
      },
      {
        order: 4,
        title: "Ajusta y conserva",
        text: "Prueba y rectifica de sal y lima. Introduce el hueso de aguacate en el centro del guacamole para retrasar la oxidación. Cubre con film a piel.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [],
      },
      {
        order: 5,
        title: "Sirve con nachos",
        text: "Sirve el guacamole en el bol o molcajete con los nachos a un lado. Consume en el mismo día — el guacamole no se conserva bien en nevera más de 24 horas.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [{ name: "Nachos" }],
      },
    ],
  },

  "quesadillas-de-queso-920ade1a": {
    description: "Tortillas de trigo dobladas con mozzarella fundida y pimiento rojo salteado, tostadas en sartén hasta conseguir una costra dorada y crujiente con el queso filante en el interior. Listas en 15 minutos.",
    prepTime: 10,
    cookTime: 15,
    difficulty: "Fácil",
    allergens: ["gluten", "lactosa"],
    tags: ["mexicano", "rápido", "vegetariano", "snack", "queso"],
    steps: [
      {
        order: 1,
        title: "Saltea el pimiento",
        text: "Corta el pimiento rojo en tiras finas. Calienta 1 cda de aceite en sartén a fuego medio-fuerte. Saltea las tiras 5-6 min hasta que estén blandas y con bordes tostados. Salpimenta.",
        hasTimer: true,
        durationMinutes: 6,
        durationSeconds: null,
        timerLabel: "Saltear pimiento",
        ingredientRefs: [{ name: "Pimiento rojo" }],
      },
      {
        order: 2,
        title: "Calienta la sartén",
        text: "Calienta una sartén grande o plancha a fuego medio. No añadas aceite — la tortilla se tuesta en seco.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [],
      },
      {
        order: 3,
        title: "Rellena y dobla",
        text: "Coloca una tortilla en la sartén. Cubre una mitad con mozzarella en trozos y el pimiento salteado. Dobla la otra mitad sobre el relleno y presiona suavemente.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [{ name: "Tortilla de trigo grande" }, { name: "Queso mozzarella" }, { name: "Pimiento rojo" }],
      },
      {
        order: 4,
        title: "Tuesta la quesadilla",
        text: "Cocina 2-3 min por lado a fuego medio hasta que la tortilla esté dorada y crujiente y el queso fundido. Usa espátula para girar con cuidado.",
        hasTimer: true,
        durationMinutes: 5,
        durationSeconds: null,
        timerLabel: "Tostado",
        ingredientRefs: [],
      },
      {
        order: 5,
        title: "Corta y sirve",
        text: "Retira la quesadilla y corta en triángulos con cortador de pizza o cuchillo grande. Sirve inmediatamente con guacamole, crema agria y salsa. Repite con las demás tortillas.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [],
      },
    ],
  },

  "sopa-de-tortilla-506fe2b0": {
    description: "Sopa mexicana caldosa con base de tomate y chile, tiras de tortilla crujientes y aguacate que se añaden en el momento de servir. Un plato de contrastes: caldo especiado caliente y toppings frescos y crujientes.",
    prepTime: 15,
    cookTime: 30,
    difficulty: "Media",
    allergens: ["gluten"],
    tags: ["mexicano", "sopa", "sin lactosa", "picante", "especiado"],
    steps: [
      {
        order: 1,
        title: "Hidrata los chiles",
        text: "Abre los chiles secos, retira semillas y venas. Sumerge en agua muy caliente 15 min hasta que se hidraten. Escurre y reserva el líquido.",
        hasTimer: true,
        durationMinutes: 15,
        durationSeconds: null,
        timerLabel: "Hidratación chiles",
        ingredientRefs: [{ name: "Chile seco" }],
      },
      {
        order: 2,
        title: "Prepara la salsa base",
        text: "Tritura los chiles hidratados con el tomate triturado, ajo y un poco del caldo. En olla, sofríe cebolla picada 5 min en aceite. Añade la salsa triturada y cocina 8-10 min a fuego medio hasta que espese.",
        hasTimer: true,
        durationMinutes: 10,
        durationSeconds: null,
        timerLabel: "Cocción base",
        ingredientRefs: [{ name: "Chile seco" }, { name: "Tomate triturado" }],
      },
      {
        order: 3,
        title: "Añade el caldo",
        text: "Incorpora el caldo de pollo caliente, sal y cuece a fuego medio 15 min. Rectifica el picante — añade más chile si deseas.",
        hasTimer: true,
        durationMinutes: 15,
        durationSeconds: null,
        timerLabel: "Cocción sopa",
        ingredientRefs: [{ name: "Caldo de pollo" }],
      },
      {
        order: 4,
        title: "Fríe las tiras de tortilla",
        text: "Corta las tortillas en tiras finas de 1 cm. Fríe en aceite caliente hasta que estén crujientes y doradas. Escurre en papel absorbente. Alterna: usa tiras de nachos comerciales.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [{ name: "Tortillas fritas en tiras" }],
      },
      {
        order: 5,
        title: "Sirve con toppings",
        text: "Sirve la sopa caliente en cuencos hondos. En el momento de servir, añade las tiras de tortilla crujientes, el aguacate en láminas, queso fresco, crema agria y cilantro. Los toppings deben añadirse al momento para conservar texturas.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [{ name: "Tortillas fritas en tiras" }, { name: "Aguacate" }],
      },
    ],
  },

  "chili-con-carne-e97bdd55": {
    description: "Guiso texano-mexicano de carne picada de ternera con alubias rojas, tomate y especias que se cocina lentamente hasta que los sabores se funden. Servido con arroz o nachos, nunca decepciona.",
    prepTime: 15,
    cookTime: 50,
    difficulty: "Fácil",
    allergens: [],
    tags: ["mexicano", "guiso", "sin gluten", "sin lactosa", "especiado", "familiar"],
    steps: [
      {
        order: 1,
        title: "Sofríe la base",
        text: "En olla grande, sofríe la cebolla y el pimiento rojo en dados en aceite 6 min a fuego medio hasta ablandar.",
        hasTimer: true,
        durationMinutes: 6,
        durationSeconds: null,
        timerLabel: "Sofrito",
        ingredientRefs: [{ name: "Cebolla" }, { name: "Pimiento rojo" }],
      },
      {
        order: 2,
        title: "Dora la carne picada",
        text: "Sube el fuego a fuerte, añade la carne picada y cocina removiendo 8-10 min hasta que pierda el color rosado y se dore ligeramente. Rompe los grumos.",
        hasTimer: true,
        durationMinutes: 10,
        durationSeconds: null,
        timerLabel: "Dorear carne",
        ingredientRefs: [{ name: "Carne picada de ternera" }],
      },
      {
        order: 3,
        title: "Tuesta las especias",
        text: "Añade ajo picado, comino, chile en polvo, pimentón dulce y orégano. Remueve 1-2 min a fuego medio para tostar las especias y liberar sus aromas.",
        hasTimer: true,
        durationMinutes: 2,
        durationSeconds: null,
        timerLabel: "Tostar especias",
        ingredientRefs: [],
      },
      {
        order: 4,
        title: "Añade tomate y alubias",
        text: "Incorpora el tomate triturado y cocina 5 min. Añade las alubias rojas escurridas, sal, pimienta y un poco de agua o caldo. Mezcla bien.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [{ name: "Tomate triturado" }, { name: "Alubias rojas cocidas" }],
      },
      {
        order: 5,
        title: "Cocina a fuego lento",
        text: "Reduce el fuego al mínimo, tapa parcialmente y cocina 30-40 min removiendo ocasionalmente. El chili debe estar espeso y oscuro. Prueba y rectifica sal y picante.",
        hasTimer: true,
        durationMinutes: 35,
        durationSeconds: null,
        timerLabel: "Cocción lenta",
        ingredientRefs: [],
      },
      {
        order: 6,
        title: "Sirve con acompañamientos",
        text: "Sirve en cuencos sobre arroz blanco o con nachos. Acompaña con queso cheddar rallado, crema agria, cebolla picada y cilantro fresco.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [],
      },
    ],
  },

  "burritos-de-ternera-f49e2c56": {
    description: "Burritos generosos de ternera especiada con arroz, alubias negras y queso cheddar fundido, envueltos en tortilla de trigo sellada en la plancha. Cada corte revela capas de sabor y textura.",
    prepTime: 20,
    cookTime: 20,
    difficulty: "Media",
    allergens: ["gluten", "lactosa"],
    tags: ["mexicano", "burrito", "familiar", "especiado", "completo"],
    steps: [
      {
        order: 1,
        title: "Cocina la ternera",
        text: "Corta la ternera en dados o tiras finas. Sazona con sal, pimienta, comino y ajo en polvo. En sartén con aceite a fuego fuerte, cocina la carne 8-10 min hasta dorar bien. Reserva.",
        hasTimer: true,
        durationMinutes: 10,
        durationSeconds: null,
        timerLabel: "Cocción ternera",
        ingredientRefs: [{ name: "Carne de ternera" }],
      },
      {
        order: 2,
        title: "Calienta rellenos",
        text: "Calienta el arroz cocido y las alubias negras escurridas por separado en microondas o sartén. Sazona las alubias con comino y sal.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [{ name: "Arroz cocido" }, { name: "Alubias negras cocidas" }],
      },
      {
        order: 3,
        title: "Calienta las tortillas",
        text: "Calienta las tortillas de trigo en sartén seca 30 seg por lado hasta que sean flexibles y ligeras. No las tuestes demasiado o se romperán al doblar.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [{ name: "Tortillas de trigo grandes" }],
      },
      {
        order: 4,
        title: "Monta el burrito",
        text: "Extiende arroz en el centro-inferior de la tortilla. Coloca carne encima, luego alubias y queso cheddar. No sobrecargues — el burrito debe cerrarse bien. Dobla los laterales hacia dentro y enrolla firmemente desde abajo.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [{ name: "Arroz cocido" }, { name: "Carne de ternera" }, { name: "Alubias negras cocidas" }, { name: "Queso cheddar rallado" }],
      },
      {
        order: 5,
        title: "Sella en la plancha",
        text: "Coloca el burrito con la unión hacia abajo en sartén caliente sin aceite. Tuesta 2 min por lado hasta que esté sellado y crujiente.",
        hasTimer: true,
        durationMinutes: 4,
        durationSeconds: null,
        timerLabel: "Sellado plancha",
        ingredientRefs: [],
      },
      {
        order: 6,
        title: "Corta y sirve",
        text: "Corta el burrito por la mitad en diagonal. Sirve con guacamole, salsa roja y crema agria a un lado.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [],
      },
    ],
  },

  "pozole-rojo-5289f5b2": {
    description: "Caldo rojo profundo y especiado con cerdo deshebrado y maíz pozolero cocido a fuego lento. Un guiso ancestral mexicano que se sirve con una corona de toppings frescos que se personalizan en la mesa.",
    prepTime: 20,
    cookTime: 75,
    difficulty: "Alta",
    allergens: [],
    tags: ["mexicano", "especial", "sin gluten", "tradicional", "fin-de-semana"],
    steps: [
      {
        order: 1,
        title: "Cuece la carne",
        text: "En olla grande, cubre la carne de cerdo con agua fría. Añade 2 dientes de ajo, sal y laurel. Lleva a ebullición, espuma y cuece a fuego medio 45-50 min hasta que la carne esté muy tierna. Reserva el caldo.",
        hasTimer: true,
        durationMinutes: 50,
        durationSeconds: null,
        timerLabel: "Cocción cerdo",
        ingredientRefs: [{ name: "Cerdo en trozos" }],
      },
      {
        order: 2,
        title: "Hidrata los chiles y prepara la salsa",
        text: "Hidrata los chiles guajillo en agua muy caliente 20 min. Escurre y tritura con los 2 dientes de ajo restantes, orégano y 2 tazas del caldo de cocción hasta obtener una salsa suave.",
        hasTimer: true,
        durationMinutes: 20,
        durationSeconds: null,
        timerLabel: "Hidratación chiles",
        ingredientRefs: [{ name: "Chile guajillo seco" }, { name: "Ajo" }, { name: "Orégano seco" }],
      },
      {
        order: 3,
        title: "Fríe la salsa de chile",
        text: "Cuela la salsa de chile. En la olla limpia, fríe la salsa colada en 2 cdas de aceite a fuego medio 5 min hasta que oscurezca y se concentre.",
        hasTimer: true,
        durationMinutes: 5,
        durationSeconds: null,
        timerLabel: "Freír salsa",
        ingredientRefs: [],
      },
      {
        order: 4,
        title: "Construye el pozole",
        text: "Añade el caldo colado, el maíz pozolero escurrido y la carne deshebrada con tenedores. Salpimenta. Cuece todo junto 20 min a fuego medio. Ajusta sal y consistencia.",
        hasTimer: true,
        durationMinutes: 20,
        durationSeconds: null,
        timerLabel: "Cocción final",
        ingredientRefs: [{ name: "Cerdo en trozos" }, { name: "Maíz pozolero cocido" }],
      },
      {
        order: 5,
        title: "Prepara los toppings",
        text: "Prepara en cuencos separados: col blanca en juliana, rábanos en rodajas, cebolla blanca picada, orégano seco, tostadas o totopos, y gajos de lima.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [],
      },
      {
        order: 6,
        title: "Sirve el pozole",
        text: "Sirve el pozole muy caliente en cuencos hondos. Cada comensal añade sus toppings: col, rábanos, cebolla, orégano y exprime lima al gusto. Las tostadas se mojan en el caldo.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [],
      },
    ],
  },

  "tostadas-de-frijol-eae9d2f2": {
    description: "Tortillas tostadas crujientes untadas con frijoles refritos calientes, coronadas con lechuga fresca, tomate en dados y crema agria. Un antojito mexicano fácil, satisfactorio y lleno de texturas.",
    prepTime: 10,
    cookTime: 10,
    difficulty: "Fácil",
    allergens: ["gluten", "lactosa"],
    tags: ["mexicano", "vegetariano", "rápido", "antojito", "económico"],
    steps: [
      {
        order: 1,
        title: "Calienta los frijoles",
        text: "Calienta los frijoles refritos en sartén con 1 cda de aceite a fuego medio 3-4 min removiendo. Sazona con comino, sal y ajo en polvo al gusto. Deben quedar bien calientes y ligeramente espesos.",
        hasTimer: true,
        durationMinutes: 4,
        durationSeconds: null,
        timerLabel: "Calentar frijoles",
        ingredientRefs: [{ name: "Frijoles refritos" }],
      },
      {
        order: 2,
        title: "Tuesta las tortillas",
        text: "Si las tortillas no son ya tostadas, hornéalas en horno a 180°C 6-8 min hasta que estén completamente crujientes, o fríelas en aceite hasta dorar. Escurre en papel.",
        hasTimer: true,
        durationMinutes: 7,
        durationSeconds: null,
        timerLabel: "Tostar tortillas",
        ingredientRefs: [{ name: "Tortillas tostadas" }],
      },
      {
        order: 3,
        title: "Prepara los toppings frescos",
        text: "Corta la lechuga en juliana fina. Pica el tomate en dados pequeños retirando las semillas. Prepara la crema agria en cuenco para servir.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [{ name: "Lechuga" }, { name: "Tomate" }],
      },
      {
        order: 4,
        title: "Monta las tostadas",
        text: "Unta cada tostada con una capa generosa de frijoles calientes llegando hasta los bordes. Coloca la lechuga, el tomate en dados y una cucharada de crema agria.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [{ name: "Frijoles refritos" }, { name: "Lechuga" }, { name: "Tomate" }, { name: "Crema agria" }],
      },
      {
        order: 5,
        title: "Sirve inmediatamente",
        text: "Sirve en el momento — las tostadas se ablandan si se dejan reposar. Añade queso fresco desmenuzado, jalapeños en escabeche y salsa picante al gusto.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [],
      },
    ],
  },

  "fajitas-de-pollo-e47269dc": {
    description: "Pollo marinado en especias teX-Mex salteado con pimientos y cebolla a fuego vivo hasta conseguir ese caramelizado irresistible. Servido en tortillas de trigo con todos los acompañamientos para que cada comensal monte la suya.",
    prepTime: 25,
    cookTime: 20,
    difficulty: "Fácil",
    allergens: ["gluten"],
    tags: ["mexicano", "fajitas", "sin lactosa*", "familiar", "colorido"],
    steps: [
      {
        order: 1,
        title: "Marina el pollo",
        text: "Corta el pollo en tiras uniformes de 1 cm. Mezcla con sal, pimienta, comino, pimentón, ajo en polvo, orégano y un chorro de lima. Marina 15 min mínimo — o toda la noche en nevera.",
        hasTimer: true,
        durationMinutes: 15,
        durationSeconds: null,
        timerLabel: "Marinado",
        ingredientRefs: [{ name: "Pollo en tiras" }],
      },
      {
        order: 2,
        title: "Corta las verduras",
        text: "Corta los pimientos rojo y verde en tiras de 1 cm del mismo grosor que el pollo. Corta la cebolla en medias lunas. Uniformidad en el corte = cocción uniforme.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [{ name: "Pimiento rojo" }, { name: "Pimiento verde" }, { name: "Cebolla" }],
      },
      {
        order: 3,
        title: "Cocina el pollo a fuego vivo",
        text: "Calienta sartén o plancha de hierro a fuego máximo. Añade aceite y cocina el pollo en tandas 4-5 min sin mover — deja que se dore bien antes de girar. Reserva.",
        hasTimer: true,
        durationMinutes: 5,
        durationSeconds: null,
        timerLabel: "Cocción pollo",
        ingredientRefs: [{ name: "Pollo en tiras" }],
      },
      {
        order: 4,
        title: "Saltea las verduras",
        text: "En la misma sartén, saltea pimientos y cebolla a fuego fuerte 5-7 min hasta que estén blandos con bordes tostados. No remuevas en exceso — el caramelizado es el objetivo.",
        hasTimer: true,
        durationMinutes: 7,
        durationSeconds: null,
        timerLabel: "Saltear verduras",
        ingredientRefs: [{ name: "Pimiento rojo" }, { name: "Pimiento verde" }, { name: "Cebolla" }],
      },
      {
        order: 5,
        title: "Junta y calienta tortillas",
        text: "Devuelve el pollo a la sartén con las verduras. Mezcla y cocina 1 min más. Calienta las tortillas en sartén seca 30 seg por lado.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [{ name: "Pollo en tiras" }, { name: "Tortillas de trigo" }],
      },
      {
        order: 6,
        title: "Sirve en la mesa",
        text: "Lleva la sartén humeante a la mesa junto a las tortillas calientes, guacamole, crema agria, salsa y queso. Cada uno monta su fajita al momento.",
        hasTimer: false,
        durationMinutes: null,
        durationSeconds: null,
        timerLabel: null,
        ingredientRefs: [],
      },
    ],
  },
};

// ─── MAIN ─────────────────────────────────────────────────────────────────────
async function main() {
  const url = resolveMongoUrl();
  const client = new MongoClient(url);
  await client.connect();
  const db = client.db();
  const packs = db.collection("catalogpacks");

  const targetSlugs = ["mediterranean-pack-vol1", "mexican-pack-vol1"];
  let totalUpdated = 0;

  for (const slug of targetSlugs) {
    const pack = await packs.findOne({ slug });
    if (!pack) { console.log(`⚠  Pack not found: ${slug}`); continue; }

    console.log(`\n── Pack: ${slug} (${pack.dishes.length} platos) ──────────────`);

    const updatedDishes = pack.dishes.map((dish) => {
      const enrichment = DISH_ENRICHMENT[dish.dishTemplateId];
      if (!enrichment) {
        console.log(`  ⚠  No enrichment for dishTemplateId: ${dish.dishTemplateId} (${dish.name})`);
        return dish;
      }

      console.log(`  ✓ ${dish.name} → ${enrichment.steps.length} pasos`);

      return {
        ...dish,
        description: enrichment.description,
        prepTime: enrichment.prepTime,
        cookTime: enrichment.cookTime,
        difficulty: enrichment.difficulty,
        allergens: enrichment.allergens,
        tags: enrichment.tags,
        recipe: {
          ...dish.recipe,
          steps: enrichment.steps,
        },
      };
    });

    if (APPLY) {
      const result = await packs.updateOne(
        { _id: pack._id },
        { $set: { dishes: updatedDishes, updatedAt: NOW } }
      );
      console.log(`  ✅ Guardado: ${result.modifiedCount} documento modificado`);
    }
    totalUpdated += updatedDishes.length;
  }

  console.log(`\n${"─".repeat(60)}`);
  console.log(`Platos procesados: ${totalUpdated}`);
  if (!APPLY) console.log("DRY-RUN — usa --apply para ejecutar.");
  else console.log("✅ APLICADO.");

  await client.close();
}

main().catch((err) => { console.error(err); process.exit(1); });
